### PR TITLE
feat: set MEILISEARCH_ENABLED in MFE_CONFIG [FC-0040]

### PR DESCRIPTION
**Pull request by rpenido**
## Description

This PR passes the MEILISEARCH_ENABLED settings to the MFE_CONFIG variable to be used in the MFEs.

## More Information
Part of:
 - https://github.com/openedx/modular-learning/issues/199

___
Internal ref: [FAL-3693](https://tasks.opencraft.com/browse/FAL-3693)

### CODE REVIEW

**Review by yusuf-musleh — APPROVED** [review]
:+1: It's working well @rpenido !

- [X] I tested this: Tested as part of related PR
- [X] I read through the code
- [ ] ~I checked for accessibility issues~
- [ ] ~Includes documentation~

**Comment by bradenmacdonald** [comment]
@rpenido If you can push your changes to the `open-craft` fork, it's much easier to test than on your own fork.

**Comment by rpenido** [comment]
> @rpenido If you can push your changes to the `open-craft` fork, it's much easier to test than on your own fork.

@bradenmacdonald 
Sorry! I forgot to mention it!
I don't have permission to create a branch at the `open-craft` fork.

**Comment by bradenmacdonald** [comment]
@rpenido Sorry about that. Fixed :)

**Pull request merged**
